server:
  port: 8084
spring:
  application:
    name: goods-page
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.228.160
    username: leyou
    password: leyou
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}.${server.port}
ly:
  thymeleaf:
    destPath: E:/develop/html/item  #在nginx里部署后, 此路径改为/usr/local/nginx/html/item, 让其自己产生自己读取